name: event_management_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  flutter_bloc: ^8.1.3
  google_fonts: ^4.0.4
  http: ^0.13.6
  jwt_decoder: ^2.0.1
  pushable_button: ^0.0.2
  shared_preferences: ^2.1.2
  flutter_animated_button: ^2.0.3
  intl: ^0.18.1
  toggle_switch: ^2.1.0
  material_dialogs: ^1.1.4
  ficonsax: ^0.0.3
  iconsax: ^0.0.8
  lottie: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 500
  uses-material-design: true
